### ISSUE TITLE
Come up with ideas on how to handle "updates"

### ISSUE THREAD

**Issue by zpeters** [zpeters/stashbox#9]
Currently, if you save the same url again it will overwrite the existing file.  it would be nice to have some sort of versioning system so that nothing is overwritten so you can eventually browse through changes

**Comment by shivamanipatil** [comment]
Hey, I was thinking of an approach like :

-  Each domain will have its own folder(same as current implementation).
-  Inside these domain folders there will be subfolders with the name such as v1, v2, .., vn corresponding to the various versions.
-  Then there will be an additional conf(yaml/json) file inside the domain folder also which will contain the latest version number and the website name so that we always know what will be the name of the next version folder.

What do you think about this approach? Can I continue working on it?

**Comment by satriarrrrr** [comment]
Can we just add the date as a prefix to the filename (filename_YYYYMMDD.pdf), so we can sort it chronologically?

**Comment by shivamanipatil** [comment]
Do you mean multiple domainName_date folders? Because currently inside the domain folder it generates file with hash names right?

**Comment by shivamanipatil** [comment]
Yeah actually we can do like that folder will have names as domainName_date+time this we ensure there will be different versions even if we did the crawling on the same day.

**Comment by zpeters** [comment]
I like the date based approach for folders.  Lets let the filenames untouched for now.  There is another PR to extract the webpage title for the file name.

Thanks!
